name: release

on:
  push:
    branches:
      - develop

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ—ƒï¸
      uses: actions/checkout@master

    - name: Restore Cached Dependencies â™»ï¸
      uses: actions/cache@master
      env:
        cache-name: cache-pnpm-modules
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

    - name: Set Up Performant NPM ğŸ”¥
      uses: pnpm/action-setup@v2
      with:
        version: 6.10
        run_install: false

    - name: Configure Performant NPM ğŸ“
      run: pnpm config set pnpm-prefix ~/.pnpm/

    - name: Add Semantic Release Dependencies ğŸ©º
      run: pnpm i -g semantic-release @semantic-release/git @semantic-release/changelog

    - name: Update Version âœ…
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: pnpx semantic-release
